version: "3"
services:
  web-client-service:
    image: gsdsolutions/web-client-service:latest
    networks:
      - frontend
    ports:
     - "80:3000"
    deploy:
      replicas: 3
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend
networks:
  frontend: